name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
        include:
          - target: x86_64-unknown-linux-musl
            rust_target: x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-musl
            rust_target: aarch64-unknown-linux-musl

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.rust_target }}
          override: true

      # Build the Rust project
      - name: Build Rust project
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.rust_target }} --release

      # Upload the artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bpm-${{ matrix.target }}
          path: target/${{ matrix.rust_target }}/release/bpm
